/**
 * Manually-curated slang / rap-vocabulary supplement.
 *
 * CMU gaps out on modern slang, contractions and rap-specific vocabulary —
 * exactly what this tool needs to be good at. This map is checked BEFORE the
 * G2P fallback (but after CMU) and is meant to grow over time as gaps surface,
 * the same way Barsmith's word-bank JSON assets do.
 *
 * Pronunciations are ARPAbet with stress digits, space-separated, lowercase key.
 * Keep entries confident and hand-verified; when unsure, leave it to G2P.
 */
export const SLANG: Record<string, string> = {
  // contractions / reductions
  finna: 'F IH1 N AH0',
  tryna: 'T R AY1 N AH0',
  gonna: 'G AA1 N AH0',
  wanna: 'W AA1 N AH0',
  gotta: 'G AA1 T AH0',
  lemme: 'L EH1 M IY0',
  gimme: 'G IH1 M IY0',
  kinda: 'K AY1 N D AH0',
  outta: 'AW1 T AH0',
  lotta: 'L AA1 T AH0',
  cuz: 'K AH1 Z',
  imma: 'AY1 M AH0',
  dunno: 'D AH0 N OW1',

  // vocabulary
  lil: 'L IH1 L',
  shawty: 'SH AO1 T IY0',
  hunnid: 'HH AH1 N IH0 D',
  thottie: 'TH AA1 T IY0',
  drip: 'D R IH1 P',
  drippy: 'D R IH1 P IY0',
  flex: 'F L EH1 K S',
  lit: 'L IH1 T',
  cap: 'K AE1 P',
  bussin: 'B AH1 S IH0 N',
  sus: 'S AH1 S',
  rizz: 'R IH1 Z',
  rizzler: 'R IH1 Z L ER0',
  gyat: 'G Y AE1 T',
  bet: 'B EH1 T',
  vibe: 'V AY1 B',
  vibes: 'V AY1 B Z',
  swag: 'S W AE1 G',
  turnt: 'T ER1 N T',
  woke: 'W OW1 K',
  savage: 'S AE1 V IH0 JH',
  clout: 'K L AW1 T',
  stan: 'S T AE1 N',
  simp: 'S IH1 M P',
  yeet: 'Y IY1 T',
  bruh: 'B R AH1',
  fam: 'F AE1 M',
  deadass: 'D EH1 D AE0 S',
  lowkey: 'L OW1 K IY0',
  highkey: 'HH AY1 K IY0',
  guap: 'G W AA1 P',
  racks: 'R AE1 K S',
  bands: 'B AE1 N D Z',
  plug: 'P L AH1 G',
  trap: 'T R AE1 P',
  whip: 'W IH1 P',
  bling: 'B L IH1 NG',
  crib: 'K R IH1 B',
  opps: 'AA1 P S',
  sheesh: 'SH IY1 SH',
  skrrt: 'S K ER1 T',
  slay: 'S L EY1',
  snatched: 'S N AE1 CH T',
  mid: 'M IH1 D',
  based: 'B EY1 S T',
  goated: 'G OW1 T IH0 D',
  gng: 'G AE1 NG',
  glizzy: 'G L IH1 Z IY0',
  cheugy: 'CH UW1 G IY0',
  drac: 'D R AE1 K',
  addy: 'AE1 D IY0',
  molly: 'M AA1 L IY0',
  finesse: 'F IH0 N EH1 S',

  // dropped-g colloquial -in forms (CMU only carries the -ing spellings)
  ballin: 'B AO1 L IH0 N',
  trippin: 'T R IH1 P IH0 N',
  flexin: 'F L EH1 K S IH0 N',
  cappin: 'K AE1 P IH0 N',
  grindin: 'G R AY1 N D IH0 N',
  wildin: 'W AY1 L D IH0 N',
  buggin: 'B AH1 G IH0 N',
  vibin: 'V AY1 B IH0 N',
  geekin: 'G IY1 K IH0 N',
  tweakin: 'T W IY1 K IH0 N',
  drippin: 'D R IH1 P IH0 N',
  stuntin: 'S T AH1 N T IH0 N',
  cattin: 'K AE1 T IH0 N',
  yappin: 'Y AE1 P IH0 N',
  trappin: 'T R AE1 P IH0 N',

  // contractions / reductions
  boutta: 'B AW1 T AH0',
  ard: 'AA1 R D',
  aight: 'AY1 T',
  yeen: 'Y IY1 N',
  ongod: 'AA1 N G AA2 D',
  finsta: 'F IH1 N S T AH0',

  // street / drug vocabulary
  perc: 'P ER1 K',
  percs: 'P ER1 K S',
  xan: 'Z AE1 N',
  xans: 'Z AE1 N Z',
  wock: 'W AA1 K',
  wockesha: 'W AA0 K EH1 SH AH0',
  zaza: 'Z AA1 Z AA0',
  za: 'Z AA1',
  terp: 'T ER1 P',
  terps: 'T ER1 P S',
  bando: 'B AE1 N D OW0',
  reup: 'R IY1 AH2 P',
  draco: 'D R AA1 K OW0',
  choppa: 'CH AA1 P AH0',
  opp: 'AA1 P',
  slatt: 'S L AE1 T',
  swerve: 'S W ER1 V',

  // brands rappers reach for
  gucci: 'G UW1 CH IY0',
  fendi: 'F EH1 N D IY0',
  versace: 'V ER0 S AA1 CH IY0',
  amiri: 'AH0 M IH1 R IY0',
  balenciaga: 'B AH0 L EH2 N S IY0 AA1 G AH0',
  forgiato: 'F AO0 R JH IY0 AA1 T OW0',
  patek: 'P AA0 T EH1 K',
  backwood: 'B AE1 K W UH2 D',
  backwoods: 'B AE1 K W UH2 D Z',
  swisher: 'S W IH1 SH ER0',

  // money
  guala: 'G W AA1 L AH0',
  moolah: 'M UW1 L AA0',
  guac: 'G W AA1 K',
  benjis: 'B EH1 N JH IY0 Z',

  // gen-z / internet
  gyatt: 'G Y AE1 T',
  fanum: 'F AE1 N AH0 M',
  delulu: 'D IH0 L UW1 L UW0',
  yap: 'Y AE1 P',
  yapping: 'Y AE1 P IH0 NG',
  glazing: 'G L EY1 Z IH0 NG',
  mewing: 'M Y UW1 IH0 NG',
  mogging: 'M AA1 G IH0 NG',
  looksmax: 'L UH1 K S M AE2 K S',
  huzz: 'HH AH1 Z',
  bruzz: 'B R AH1 Z',
  crashout: 'K R AE1 SH AW2 T',
  pookie: 'P UH1 K IY0',
  ick: 'IH1 K',
  goon: 'G UW1 N',
  gooning: 'G UW1 N IH0 NG',
  pilled: 'P IH1 L D',
  redpilled: 'R EH1 D P IH2 L D',
  sigma: 'S IH1 G M AH0',
  skibidi: 'S K IH1 B IH0 D IY0',
  cooked: 'K UH1 K T',
  npc: 'EH2 N P IY2 S IY1',

  // adlibs / interjections
  skrt: 'S K ER1 T',
  woo: 'W UW1',
  esskeetit: 'EH2 S K IY1 T IH0 T',
  glo: 'G L OW1',
  froze: 'F R OW1 Z',
};

/**
 * Curated CMU-gap words seeded directly from Barsmith's own hand-authored
 * pronunciation supplement (src/data/pronunciation-extra.json) — loanwords and
 * coinages CMU does not carry and no derivation rule reaches. Kept as a
 * separate block so its provenance stays clear; folded into SUPPLEMENT below.
 */
export const CURATED: Record<string, string> = {
  affray: 'AH0 F R EY1',
  arpeggio: 'AA0 R P EH1 JH IY0 OW0',
  balustrade: 'B AE1 L AH0 S T R EY2 D',
  bodacious: 'B OW0 D EY1 SH AH0 S',
  cerebrum: 'S ER0 IY1 B R AH0 M',
  ceremonious: 'S EH2 R AH0 M OW1 N IY0 AH0 S',
  cherubim: 'CH EH1 R AH0 B IH0 M',
  chronometer: 'K R AH0 N AA1 M AH0 T ER0',
  crinoline: 'K R IH1 N AH0 L IH0 N',
  cummerbund: 'K AH1 M ER0 B AH2 N D',
  didgeridoo: 'D IH1 JH ER0 IY0 D UW2',
  dirigible: 'D IH1 R AH0 JH AH0 B AH0 L',
  doppelganger: 'D AA1 P AH0 L G AE2 NG ER0',
  dungarees: 'D AH2 NG G ER0 IY1 Z',
  emotionality: 'IH0 M OW2 SH AH0 N AE1 L AH0 T IY0',
  gramophone: 'G R AE1 M AH0 F OW2 N',
  grenadier: 'G R EH2 N AH0 D IH1 R',
  griddle: 'G R IH1 D AH0 L',
  hibiscus: 'HH AY0 B IH1 S K AH0 S',
  incubus: 'IH1 NG K Y AH0 B AH0 S',
  jamboree: 'JH AE2 M B ER0 IY1',
  lamentation: 'L AE2 M AH0 N T EY1 SH AH0 N',
  laze: 'L EY1 Z',
  macaroon: 'M AE2 K ER0 UW1 N',
  minotaur: 'M IH1 N AH0 T AO2 R',
  mongrel: 'M AA1 NG G R AH0 L',
  nectarine: 'N EH2 K T ER0 IY1 N',
  negligee: 'N EH2 G L AH0 ZH EY1',
  obelisk: 'AA1 B AH0 L IH0 S K',
  objectification: 'AH0 B JH EH2 K T AH0 F AH0 K EY1 SH AH0 N',
  papyrus: 'P AH0 P AY1 R AH0 S',
  pedometer: 'P AH0 D AA1 M AH0 T ER0',
  pimento: 'P AH0 M EH1 N T OW0',
  prolongation: 'P R OW2 L AO0 NG G EY1 SH AH0 N',
  promontory: 'P R AA1 M AH0 N T AO2 R IY0',
  quesadilla: 'K EY2 S AH0 D IY1 Y AH0',
  reliquary: 'R EH1 L AH0 K W EH2 R IY0',
  rend: 'R EH1 N D',
  satchel: 'S AE1 CH AH0 L',
  scepter: 'S EH1 P T ER0',
  scimitar: 'S IH1 M AH0 T ER0',
  seismograph: 'S AY1 Z M AH0 G R AE2 F',
  seraph: 'S EH1 R AH0 F',
  splay: 'S P L EY1',
  sprig: 'S P R IH1 G',
  stalactite: 'S T AH0 L AE1 K T AY2 T',
  strop: 'S T R AA1 P',
  sycophant: 'S IH1 K AH0 F AH0 N T',
  systematization: 'S IH2 S T AH0 M AH0 T AH0 Z EY1 SH AH0 N',
  systematize: 'S IH1 S T AH0 M AH0 T AY2 Z',
  tapioca: 'T AE2 P IY0 OW1 K AH0',
  terrarium: 'T ER0 EH1 R IY0 AH0 M',
  trawl: 'T R AO1 L',
  trebuchet: 'T R EH1 B Y UW0 SH EH2 T',
  vermicelli: 'V ER2 M AH0 CH EH1 L IY0',
  virtualization: 'V ER2 CH UW0 AH0 L AH0 Z EY1 SH AH0 N',
  wasabi: 'W AH0 S AA1 B IY0',
  weaponization: 'W EH2 P AH0 N AH0 Z EY1 SH AH0 N',
  weaponize: 'W EH1 P AH0 N AY2 Z',
};

/** The full curated supplement: slang + Barsmith's CMU-gap words. */
export const SUPPLEMENT: Record<string, string> = { ...CURATED, ...SLANG };
