/**
 * Manually-curated slang / rap-vocabulary supplement.
 *
 * CMU gaps out on modern slang, contractions and rap-specific vocabulary —
 * exactly what this tool needs to be good at. This map is checked BEFORE the
 * G2P fallback (but after CMU) and is meant to grow over time as gaps surface,
 * the same way Barsmith's word-bank JSON assets do.
 *
 * Pronunciations are ARPAbet with stress digits, space-separated, lowercase key.
 * Keep entries confident and hand-verified; when unsure, leave it to G2P.
 */
export const SLANG: Record<string, string> = {
  // contractions / reductions
  finna: 'F IH1 N AH0',
  tryna: 'T R AY1 N AH0',
  gonna: 'G AA1 N AH0',
  wanna: 'W AA1 N AH0',
  gotta: 'G AA1 T AH0',
  lemme: 'L EH1 M IY0',
  gimme: 'G IH1 M IY0',
  kinda: 'K AY1 N D AH0',
  outta: 'AW1 T AH0',
  lotta: 'L AA1 T AH0',
  cuz: 'K AH1 Z',
  imma: 'AY1 M AH0',
  dunno: 'D AH0 N OW1',

  // vocabulary
  lil: 'L IH1 L',
  shawty: 'SH AO1 T IY0',
  hunnid: 'HH AH1 N IH0 D',
  thottie: 'TH AA1 T IY0',
  drip: 'D R IH1 P',
  drippy: 'D R IH1 P IY0',
  flex: 'F L EH1 K S',
  lit: 'L IH1 T',
  cap: 'K AE1 P',
  bussin: 'B AH1 S IH0 N',
  sus: 'S AH1 S',
  rizz: 'R IH1 Z',
  rizzler: 'R IH1 Z L ER0',
  gyat: 'G Y AE1 T',
  bet: 'B EH1 T',
  vibe: 'V AY1 B',
  vibes: 'V AY1 B Z',
  swag: 'S W AE1 G',
  turnt: 'T ER1 N T',
  woke: 'W OW1 K',
  savage: 'S AE1 V IH0 JH',
  clout: 'K L AW1 T',
  stan: 'S T AE1 N',
  simp: 'S IH1 M P',
  yeet: 'Y IY1 T',
  bruh: 'B R AH1',
  fam: 'F AE1 M',
  deadass: 'D EH1 D AE0 S',
  lowkey: 'L OW1 K IY0',
  highkey: 'HH AY1 K IY0',
  guap: 'G W AA1 P',
  racks: 'R AE1 K S',
  bands: 'B AE1 N D Z',
  plug: 'P L AH1 G',
  trap: 'T R AE1 P',
  whip: 'W IH1 P',
  bling: 'B L IH1 NG',
  crib: 'K R IH1 B',
  opps: 'AA1 P S',
  sheesh: 'SH IY1 SH',
  skrrt: 'S K ER1 T',
  slay: 'S L EY1',
  snatched: 'S N AE1 CH T',
  mid: 'M IH1 D',
  based: 'B EY1 S T',
  goated: 'G OW1 T IH0 D',
  gng: 'G AE1 NG',
  glizzy: 'G L IH1 Z IY0',
  cheugy: 'CH UW1 G IY0',
  drac: 'D R AE1 K',
  addy: 'AE1 D IY0',
  molly: 'M AA1 L IY0',
  finesse: 'F IH0 N EH1 S',
};

/**
 * Curated CMU-gap words seeded directly from Barsmith's own hand-authored
 * pronunciation supplement (src/data/pronunciation-extra.json) — loanwords and
 * coinages CMU does not carry and no derivation rule reaches. Kept as a
 * separate block so its provenance stays clear; folded into SUPPLEMENT below.
 */
export const CURATED: Record<string, string> = {
  affray: 'AH0 F R EY1',
  arpeggio: 'AA0 R P EH1 JH IY0 OW0',
  balustrade: 'B AE1 L AH0 S T R EY2 D',
  bodacious: 'B OW0 D EY1 SH AH0 S',
  cerebrum: 'S ER0 IY1 B R AH0 M',
  ceremonious: 'S EH2 R AH0 M OW1 N IY0 AH0 S',
  cherubim: 'CH EH1 R AH0 B IH0 M',
  chronometer: 'K R AH0 N AA1 M AH0 T ER0',
  crinoline: 'K R IH1 N AH0 L IH0 N',
  cummerbund: 'K AH1 M ER0 B AH2 N D',
  didgeridoo: 'D IH1 JH ER0 IY0 D UW2',
  dirigible: 'D IH1 R AH0 JH AH0 B AH0 L',
  doppelganger: 'D AA1 P AH0 L G AE2 NG ER0',
  dungarees: 'D AH2 NG G ER0 IY1 Z',
  emotionality: 'IH0 M OW2 SH AH0 N AE1 L AH0 T IY0',
  gramophone: 'G R AE1 M AH0 F OW2 N',
  grenadier: 'G R EH2 N AH0 D IH1 R',
  griddle: 'G R IH1 D AH0 L',
  hibiscus: 'HH AY0 B IH1 S K AH0 S',
  incubus: 'IH1 NG K Y AH0 B AH0 S',
  jamboree: 'JH AE2 M B ER0 IY1',
  lamentation: 'L AE2 M AH0 N T EY1 SH AH0 N',
  laze: 'L EY1 Z',
  macaroon: 'M AE2 K ER0 UW1 N',
  minotaur: 'M IH1 N AH0 T AO2 R',
  mongrel: 'M AA1 NG G R AH0 L',
  nectarine: 'N EH2 K T ER0 IY1 N',
  negligee: 'N EH2 G L AH0 ZH EY1',
  obelisk: 'AA1 B AH0 L IH0 S K',
  objectification: 'AH0 B JH EH2 K T AH0 F AH0 K EY1 SH AH0 N',
  papyrus: 'P AH0 P AY1 R AH0 S',
  pedometer: 'P AH0 D AA1 M AH0 T ER0',
  pimento: 'P AH0 M EH1 N T OW0',
  prolongation: 'P R OW2 L AO0 NG G EY1 SH AH0 N',
  promontory: 'P R AA1 M AH0 N T AO2 R IY0',
  quesadilla: 'K EY2 S AH0 D IY1 Y AH0',
  reliquary: 'R EH1 L AH0 K W EH2 R IY0',
  rend: 'R EH1 N D',
  satchel: 'S AE1 CH AH0 L',
  scepter: 'S EH1 P T ER0',
  scimitar: 'S IH1 M AH0 T ER0',
  seismograph: 'S AY1 Z M AH0 G R AE2 F',
  seraph: 'S EH1 R AH0 F',
  splay: 'S P L EY1',
  sprig: 'S P R IH1 G',
  stalactite: 'S T AH0 L AE1 K T AY2 T',
  strop: 'S T R AA1 P',
  sycophant: 'S IH1 K AH0 F AH0 N T',
  systematization: 'S IH2 S T AH0 M AH0 T AH0 Z EY1 SH AH0 N',
  systematize: 'S IH1 S T AH0 M AH0 T AY2 Z',
  tapioca: 'T AE2 P IY0 OW1 K AH0',
  terrarium: 'T ER0 EH1 R IY0 AH0 M',
  trawl: 'T R AO1 L',
  trebuchet: 'T R EH1 B Y UW0 SH EH2 T',
  vermicelli: 'V ER2 M AH0 CH EH1 L IY0',
  virtualization: 'V ER2 CH UW0 AH0 L AH0 Z EY1 SH AH0 N',
  wasabi: 'W AH0 S AA1 B IY0',
  weaponization: 'W EH2 P AH0 N AH0 Z EY1 SH AH0 N',
  weaponize: 'W EH1 P AH0 N AY2 Z',
};

/** The full curated supplement: slang + Barsmith's CMU-gap words. */
export const SUPPLEMENT: Record<string, string> = { ...CURATED, ...SLANG };
